services:
  # Actions Runner application
  app:
    image: actions-runner
    container_name: gha-runner
    restart: unless-stopped
    env_file:
      - ./.env
    # Set environment variables
    environment:
      - REPO=$REPO
      - REG_TOKEN=$REG_TOKEN
      # adding python path to add our custom persistent lib location
      - PYTHONPATH=/usr/lib/python312.zip:/usr/lib/python3.12:/usr/lib/python3.12/lib-dynload:/usr/lib/python3.12/site-packages
    # allow interactive shell
    stdin_open: true
    # allow terminal
    tty: true


